name: CI

on: 
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v6
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install test deps
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov

    - name: Run tests with coverage
      run: |
        pytest --cov=library_service --cov-report=xml tests/
    - name: Initialize database
      run: |
        python - <<'PYCODE'
        from database import get_db_connection
        conn = get_db_connection()
        conn.executescript("""
            CREATE TABLE IF NOT EXISTS books (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL,
                author TEXT NOT NULL,
                isbn TEXT UNIQUE NOT NULL,
                copies INTEGER NOT NULL DEFAULT 0,
                available INTEGER NOT NULL DEFAULT 0
            );
        """)
        conn.commit()
        conn.close()
        PYCODE

